name: ticketing_app
description: A Flutter ticketing application with payment integration.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.19.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Icon dan UI
  cupertino_icons: ^1.0.2
  flutter_svg: ^2.0.7

  # Firebase Core dan Firestore
  firebase_core: ^2.25.4
  cloud_firestore: ^4.14.0

  # State Management
  provider: ^6.1.1

  # Utilitas tambahan
  intl: ^0.18.1
  url_launcher: ^6.2.5
  path_provider: ^2.1.2
  flutter_local_notifications: ^16.3.2
  share_plus: ^7.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/ticketing_app_image.png  # Add this line for your specific image